name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/dotnet.yml'
      - 'binding/dotnet/**'
      - '!binding/dotnet/README.md'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/.test/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/dotnet.yml'
      - 'binding/dotnet/**'
      - '!binding/dotnet/README.md'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/.test/**'

defaults:
  run:
    working-directory: binding/dotnet

jobs:
  build-self-hosted:
    runs-on: ${{ matrix.machine }}
    env:
      ACCESS_KEY: ${{secrets.PV_VALID_ACCESS_KEY}}
      MODEL_PATH: ../../../../phi2-290.pllm
      DEVICE: ${{matrix.device}}

    strategy:
      fail-fast: false
      matrix:
        device: [ cpu ]
        machine: [ rpi4-32, rpi4-64, rpi5-32, rpi5-64, pv-linux, pv-ios, pv-windows, pv-windows-arm64 ]
        include:
          - device: gpu
            machine: pv-windows
          - device: gpu
            machine: pv-linux
          - device: gpu
            machine: pv-windows-igpu


    steps:
    - uses: actions/checkout@v3

    - name: Download resource files
      run: curl http://${{secrets.PV_CICD_RES_SERVER_AUTHORITY}}/github/picollm/res/phi2-290.pllm/05-f5a103d/phi2-290.pllm -o phi2-290.pllm
      working-directory: binding/dotnet

    - name: Build binding
      run: dotnet build PicoLLM/PicoLLM.csproj

    - name: Test
      run: dotnet test -v n
      env:
        DOTNET_ROLL_FORWARD: LatestMajor
